#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${HERE}/usr/lib/x86_64-linux-gnu/:$HERE/lib/x86_64-linux-gnu/:$HERE/usr/lib/:${HERE}/lib/:$LD_LIBRARY_PATH
export PATH=${HERE}/usr/sbin:${HERE}/usr/bin:$PATH
export SSL_CERT_FILE=${HERE}/usr/share/cacert.pem
export APPIMAGE="0"
"${HERE}"/usr/bin/sharexin "$@"
