version: "0.1.0.{build}"
environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
  - erase rust-install.exe
build_script:
  - cargo build
  # Skip packaging step while we're running off a local winapi build
  #- cargo package
skip_commits:
  files:
    - README.md
    - .travis.yml
